# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: nodejs continuous integration

on:
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      
    - name: Run super-linter
      uses: github/super-linter@v3

    - name: Use Node.js 16.14
      uses: actions/setup-node@v2
      with:
        node-version: 16.14.0
        cache: 'npm'
    - run: npm ci 
    - run: npm run build --if-present
    - run: npm test
