version: 0.0
os: linux
files:
 - source: .
   destination: /www/var/
hooks:
  AfterInstall:
   - location: scripts/install_node.sh
     timeout: 120
     runas: root
  ApplicationStart:
   - location: scripts/start_server.sh
     timeout: 120
     runas: root