version: 0.0
os: linux
files:
 - source: /
   destination: /var/www/
hooks:
  AfterInstall:
   - location: scripts/install_node.sh
     timeout: 440
     runas: root
  ApplicationStart:
   - location: scripts/start_server.sh
     timeout: 230
     runas: root
